export const startups = [
  {
    id: "4kwqmh20s76z120",
    first_name: "Rudy",
    last_name: "Kosashi",
    phone: "085694503272",
    email_address: "rudi.k@artique-agency.com",
    job_title: "Partnership",
    startup_name: "Artique",
    website: "artique.com",
    country: "Indonesia",
    collaborate: "All entity",
    file_proposal: "sadasdASDaks",
  },
  {
    id: "5nxph31t87y231",
    first_name: "Maya",
    last_name: "Rodriguez",
    phone: "+1 (415) 555-0123",
    email_address: "maya.r@innovatech.com",
    job_title: "CTO",
    startup_name: "InnovaTech",
    website: "innovatech.com",
    country: "United States",
    collaborate: "Tech Startups",
    file_proposal: "innovaProposal2025",
  },
  {
    id: "6opqi42u98z342",
    first_name: "Akira",
    last_name: "Tanaka",
    phone: "+81 (03) 1234-5678",
    email_address: "akira.t@greensolve.jp",
    job_title: "Founder",
    startup_name: "GreenSolve",
    website: "greensolve.jp",
    country: "Japan",
    collaborate: "Sustainability Sector",
    file_proposal: "greenSolveInitiative",
  },
  {
    id: "7pqrj53v09a453",
    first_name: "Emma",
    last_name: "Schmidt",
    phone: "+49 (030) 901-8374",
    email_address: "emma.s@techbridge.de",
    job_title: "CEO",
    startup_name: "TechBridge",
    website: "techbridge.de",
    country: "Germany",
    collaborate: "Digital Transformation",
    file_proposal: "techBridgeStrategy",
  },
  {
    id: "8rskl64w10b564",
    first_name: "Carlos",
    last_name: "Mendoza",
    phone: "+52 (55) 1234-5678",
    email_address: "carlos.m@solarlabs.mx",
    job_title: "Head of Innovation",
    startup_name: "SolarLabs",
    website: "solarlabs.mx",
    country: "Mexico",
    collaborate: "Renewable Energy",
    file_proposal: "solarInnovationPlan",
  },
  {
    id: "9stlm75x21c675",
    first_name: "Sophie",
    last_name: "Laurent",
    phone: "+33 (01) 2345-6789",
    email_address: "sophie.l@agrotech.fr",
    job_title: "Research Director",
    startup_name: "AgroTech",
    website: "agrotech.fr",
    country: "France",
    collaborate: "Agricultural Innovation",
    file_proposal: "smartFarmingInitiative",
  },
  {
    id: "10tumn86y32d786",
    first_name: "Raj",
    last_name: "Patel",
    phone: "+91 (022) 4567-8901",
    email_address: "raj.p@healthinnovate.in",
    job_title: "Co-Founder",
    startup_name: "HealthInnovate",
    website: "healthinnovate.in",
    country: "India",
    collaborate: "Medical Technology",
    file_proposal: "healthTechDisruption",
  },
  {
    id: "11uvno97z43e897",
    first_name: "Liam",
    last_name: "O'Connor",
    phone: "+353 (01) 234-5678",
    email_address: "liam.o@fintech.ie",
    job_title: "Product Manager",
    startup_name: "FinTech Solutions",
    website: "fintechsolutions.ie",
    country: "Ireland",
    collaborate: "Financial Services",
    file_proposal: "digitalBankingStrategy",
  },
  {
    id: "12vwop08a54f908",
    first_name: "Kim",
    last_name: "Soo-Jin",
    phone: "+82 (02) 3456-7890",
    email_address: "kim.s@aibridge.kr",
    job_title: "AI Researcher",
    startup_name: "AIBridge",
    website: "aibridge.kr",
    country: "South Korea",
    collaborate: "Artificial Intelligence",
    file_proposal: "aiEthicsFramework",
  },
  {
    id: "13wxpq19b65g019",
    first_name: "Ahmed",
    last_name: "Hassan",
    phone: "+971 (04) 456-7890",
    email_address: "ahmed.h@smartcity.ae",
    job_title: "Urban Innovation Lead",
    startup_name: "SmartCity Solutions",
    website: "smartcitysolutions.ae",
    country: "United Arab Emirates",
    collaborate: "Urban Development",
    file_proposal: "smartCityBlueprint",
  },
  {
    id: "14xyrq20c76h120",
    first_name: "Maria",
    last_name: "Silva",
    phone: "+55 (11) 2345-6789",
    email_address: "maria.s@edtech.br",
    job_title: "Education Innovator",
    startup_name: "EdTech Brazil",
    website: "edtechbrazil.com.br",
    country: "Brazil",
    collaborate: "Educational Technology",
    file_proposal: "digitalLearningPlatform",
  },
  {
    id: "15yzsr31d87i231",
    first_name: "Peter",
    last_name: "Andersen",
    phone: "+45 (33) 45-67-89",
    email_address: "peter.a@cleantech.dk",
    job_title: "Sustainability Director",
    startup_name: "CleanTech Denmark",
    website: "cleantechdenmark.dk",
    country: "Denmark",
    collaborate: "Environmental Solutions",
    file_proposal: "carbonNeutralityProject",
  },
  {
    id: "16zats42e98j342",
    first_name: "Elena",
    last_name: "Petrova",
    phone: "+7 (495) 123-4567",
    email_address: "elena.p@quantumtech.ru",
    job_title: "Quantum Computing Lead",
    startup_name: "QuantumTech Russia",
    website: "quantumtechrussia.ru",
    country: "Russia",
    collaborate: "Advanced Computing",
    file_proposal: "quantumAlgorithmResearch",
  },
  {
    id: "17abut53f09k453",
    first_name: "David",
    last_name: "Chen",
    phone: "+886 (02) 2345-6789",
    email_address: "david.c@biotech.tw",
    job_title: "Chief Science Officer",
    startup_name: "BioTech Taiwan",
    website: "biotechtaiwain.tw",
    country: "Taiwan",
    collaborate: "Biotechnology",
    file_proposal: "genomicInnovationPlan",
  },
  {
    id: "18bcvu64g10l564",
    first_name: "Isabella",
    last_name: "Moretti",
    phone: "+39 (06) 3456-7890",
    email_address: "isabella.m@foodtech.it",
    job_title: "Innovation Manager",
    startup_name: "FoodTech Italy",
    website: "foodtechitaly.it",
    country: "Italy",
    collaborate: "Culinary Innovation",
    file_proposal: "sustainableFoodSystems",
  },
  {
    id: "19cdwv75h21m675",
    first_name: "Mohammed",
    last_name: "Al-Fayed",
    phone: "+966 (01) 234-5678",
    email_address: "mohammed.a@energytech.sa",
    job_title: "Energy Solutions Architect",
    startup_name: "EnergyTech Saudi",
    website: "energytech.sa",
    country: "Saudi Arabia",
    collaborate: "Energy Transformation",
    file_proposal: "renewableEnergyStrategy",
  },
  {
    id: "20dexw86i32n786",
    first_name: "Sarah",
    last_name: "Thompson",
    phone: "+64 (09) 345-6789",
    email_address: "sarah.t@agritech.nz",
    job_title: "Agricultural Innovations Lead",
    startup_name: "AgriTech New Zealand",
    website: "agritechnz.co.nz",
    country: "New Zealand",
    collaborate: "Agricultural Technology",
    file_proposal: "smartFarmingInnovation",
  },
  {
    id: "21efxy97j43o897",
    first_name: "Lucas",
    last_name: "Müller",
    phone: "+41 (044) 456-7890",
    email_address: "lucas.m@cryptotech.ch",
    job_title: "Blockchain Strategist",
    startup_name: "CryptoTech Switzerland",
    website: "cryptotech.ch",
    country: "Switzerland",
    collaborate: "Blockchain Innovation",
    file_proposal: "decentralizedFinancePlan",
  },
  {
    id: "22fgyz08k54p908",
    first_name: "Olivia",
    last_name: "Park",
    phone: "+65 (06) 5678-9012",
    email_address: "olivia.p@financetech.sg",
    job_title: "Fintech Innovations Director",
    startup_name: "FinanceTech Singapore",
    website: "financetechsg.com",
    country: "Singapore",
    collaborate: "Financial Innovations",
    file_proposal: "digitalPaymentSolutions",
  },
  {
    id: "23ghza19l65q019",
    first_name: "Alex",
    last_name: "Novak",
    phone: "+380 (044) 234-5678",
    email_address: "alex.n@techinnovate.ua",
    job_title: "Innovation Consultant",
    startup_name: "TechInnovate Ukraine",
    website: "techinnovate.ua",
    country: "Ukraine",
    collaborate: "Technology Consulting",
    file_proposal: "innovationEcosystemDevelopment",
  },
  {
    id: "24hibz20m76r120",
    first_name: "Julia",
    last_name: "Kimura",
    phone: "+81 (03) 6789-0123",
    email_address: "julia.k@robotics.jp",
    job_title: "Robotics Engineering Lead",
    startup_name: "Advanced Robotics Japan",
    website: "advancedrobotics.jp",
    country: "Japan",
    collaborate: "Robotics and AI",
    file_proposal: "humanoidRoboticsResearch",
  },
];
